### ISSUE TITLE
.round method

### ISSUE THREAD

**Issue by danielmahal** [segment-boneyard/date-math#2]
First, thank you for this library. Does what I need in a very neat way. One question– `floor` and `ceil` methods exist, but why no `round`? Am I missing something?

```
Dates.day.round(new Date());
```

**Comment by calvinfo** [comment]
Not really! Other than us not really having a use case for it. Happy to
accept a PR

It'd be pretty easy to add in the same way that we have diff, something
like:

```
function round(interval){
  return function(date){
    var floored = interval.floor(date);
    var ceiled = interval.ceil(date);
    return Math.abs(floored - date) < Math.abs(ceiled - date)
      ? floored
      : ceiled;
  };
}
```

**Comment by danielmahal** [comment]
Nevermind, found out I really didn’t need it either. Maybe no one ever will :) But thanks a lot for your quick reply!
